---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId:
  directoryPerms: "700"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #TODO - name
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
    storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #TODO - name
spec:
  selector:
    matchLabels:
      app: #TODO - name
  replicas: 3
  template:
    metadata:
      labels:
        app: #TODO - name
    spec:
      containers:
        - name: #TODO - name
          image: #TODO- image
          resource:
            limits:
              memory: "4Gi"
              cpu: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: #TODO - name
              mountPath: / #TODO - name
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - # TODO - values
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: #TODO - name
          persistentVolumeClaim:
            claimName: #TODO - name
