---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-training-cluster-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi #5GB of storage